// <auto-generated />
namespace yarn_rider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AnnoInReview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AnnoInReview));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101104161_AnnoInReview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
