// <auto-generated />
namespace yarn_rider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DateAnnoFullDate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DateAnnoFullDate));
        
        string IMigrationMetadata.Id
        {
            get { return "201906101114464_DateAnnoFullDate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
